server:
  servlet:
    encoding:
      charset: utf-8
      force: true
  port: 8080

# 로그 레벨의 개념
# ERROR > WARN > INFO > DEBUG > TRACE
logging:
  level:
    root: INFO  # 모든 라이브러리는 INFO 이상만 출력
    com.tenco: DEBUG # 내 프로젝트는 DEBUG 이상 모두 출력
    #com.tenco.blog: INFO
    #com.tenco.user: WARN
# spring 환경 설정 
spring:
  datasource:
    #driver-class-name: com.mysql.cj.jdbc.Driver
    #url: jdbc:mysql://localhost:3306/blog?useSSl=false&serverTimezone=Asia/Seoul
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/blog?useSSl=false&serverTimezone=Asia/Seoul
    username: root
    password: asd1234
  # H2 데이터베이스 웹 콘솔 활성화 (개발용)
  # http://localhost:8080/h2-console
  h2:
    console:
      enabled: true

  sql:
    init:
      # 2.5 이상 버전부터 명시를 해야 insert 처리 됨
      mode: always
      data-locations:
        - classpath:db/data.sql

  # JPA 설정
  jpa:
    open-in-view: true  # 기본값 true
    hibernate:
      # create: 애플리케이션 시작시 테이블을 새로 생성
      # 기존 데이터는 모두 삭제됨 (개발용)
      ddl-auto: create
    # SQL 쿼리를 콘솔에 출력 (개발용 디버깅)
    show-sql: true
    properties:
      hibernate:
        # SQL 쿼리를 보기 좋게 포맷팅
        format_sql: true
        # in query 선택
        default_batch_fetch_size: 10
    # data.sql 파일을 Hibernate 초기화 이후에 실행
    defer-datasource-initialization: true
    # 기본값 : 엔티티 - 카멜케이스 -> db 생성될 스네이크 케이스로 자동으로 설정 됨
